name: Imaging Cloud Action Test
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
jobs:
  run-imaging-cloud-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run IL-CLI
        env:
            IC_VERSION: 1
            IC_REPO_URL: ${{github.ref}}
        run: |
          echo ${{github.ref}}
          echo ${{env.IC_VERSION}}
          echo ${{env.IC_REPO_URL}}
          cd ${{github.workspace}}
          docker run -e IMAGING_CLOUD_API_KEY=${{secrets.IMAGING_CLOUD_API_KEY}} -v $(pwd):/home/carl/extras/source castbuild/imaging-cloud-action:dev
