name: Imaging Cloud Action Test
on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:
jobs:
  run-imaging-cloud-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Pull docker image
        run: docker pull 
      - name: Run IL-CLI
        run: |
          cd ${{github.workspace}}
          docker run -e IMAGING_CLOUD_API_KEY=${{secrets.IMAGING_CLOUD_API_KEY}} -v $(pwd):/home/carl/extras/source castbuild/imaging-cloud-action:latest
